### PR TITLE
#73 Backend List All My Questions

### PR DESCRIPTION
**Pull request by ChenChenYellow**

### CODE REVIEW

**Review by AutoSleep — COMMENTED** [review]
Please write the test case for this functionality and pass the test case

**Comment by ChenChenYellow** [comment]
> Please write the test case for this functionality and pass the test case

Ok, Done

**Comment by ChenChenYellow** [comment]
image
Notice that the function returns an array
field "_id" is the Question_ID, we can use this Question_ID to navigate to the page where the the detail of this question is displayed

**Comment by AutoSleep** [comment]
The problem solved

**Pull request merged**
