### PR TITLE
#69 Backend vote answer implemented

### PR DESCRIPTION
**Pull request by ChenChenYellow**
Backend vote answer implemented

### CODE REVIEW

**Comment by ChenChenYellow** [comment]
image
image

**Comment by AutoSleep** [comment]
Please resolve the conflict and pass the test case

**Comment by ChenChenYellow** [comment]
> Please resolve the conflict and pass the test case

Conflict resolved

**Comment by AutoSleep** [comment]
The conflict is solved and can be merged

**Pull request merged**
