### PR TITLE
#109 - Improve ListAnswers Function

### PR DESCRIPTION
**Pull request by massdarkness11**
Modified the ListAnswers get to retrieve the answer username from the user database.

### CODE REVIEW

**Comment by massdarkness11** [comment]
this resolves issue #109

**Review by ChenChenYellow — CHANGES_REQUESTED** [review]
ListAnswers retrieves the Answers of a given question with a given QuestionID.
Right now this function retrives all the answers of all the questions.
Are you missing a $match?

**Comment by massdarkness11** [comment]
yeah, thanks for reviewing @ChenChenYellow, it should work better now.

**Review by ChenChenYellow — COMMENTED** [review]
The listAnswers function works as expected. Now can you implement the test for that function also?

**Comment by DrakeHunterK7** [comment]
@ChenChenYellow We will write the tests for List Answers as part of a Sprint 4 test megatask where we will write all tests at once. For now you can approve and merge this pull request if the ListAnswers function is completely working.

**Comment by ChenChenYellow** [comment]
> @ChenChenYellow We will write the tests for List Answers as part of a Sprint 4 megatask where we will write all tests at once. For now you can approve and merge this pull request if the ListAnswers function is completely working.

OK

**Review by ChenChenYellow — APPROVED** [review]

**Comment by AutoSleep** [comment]
image
It will be better to write the test case in this case.

**Comment by AutoSleep** [comment]
@massdarkness11  Can you revert this PR and write the test case and push it again
Thank you for your effort that you put in here

**Pull request merged**
