### PR TITLE
#75 Backend List All My Answers Implemented

### PR DESCRIPTION
**Pull request by ChenChenYellow**
image
Notice that this function returns an array.
Notice that the "_id" in the second blue circle indicate the ID of the Question of this Answer.
We can use this Question_id to navigate to the page of this question, and the user's answer should be this question.
Notice that in the third blue circle lies some information of the answer, they can be displayed

### CODE REVIEW

**Comment by ChenChenYellow** [comment]
I didn't do test yet, I am waiting for pr of #73 to pass, because tests are ordered

**Comment by AutoSleep** [comment]
Please solve the conflict

**Comment by AutoSleep** [comment]
Please solve the conflict

**Review by AutoSleep — APPROVED** [review]
The problem is being solved, can be merged to the main

**Pull request merged**
