### PR TITLE
# 111 Backend Notifications of Questions implemented

### PR DESCRIPTION
**Pull request by ChenChenYellow**
image

First of all,  when someone Vote a Question OR when someone Answer a Question,
the Owner of the Question will receive a Notification in his Notifications array. (Shown in yellow circle)

Then, the Type "Vote" indicate its Notification for a new Vote
the Type "Answer" indicate a Notification for a new Answer

image
Then when we Get from /notifications
If the Type is "Answer" then it will contain the Question_ID where the new Answer belong, AND the Count field indicate how many new Answers has been posted under this Question

If the Type is "Vote" then it will contain the Question_ID where the vote occurs, AND the Count field indicate the total vote change of this Question. (In the case of picture, it is 0 because someone upvoted and someone else downvoted, hence the total vote change is 0)

image

Also if we employ the DELETE from /notifications, it will delete all Notifications of the user. It will be useful to clear up old Notifications

### CODE REVIEW

**Review by DrakeHunterK7 — CHANGES_REQUESTED** [review]
Hi, bro. Looks good overall. Just three things:

1) Could you add one more delete function that deletes only one individual notification from the notification array? You already have a delete function for deleting the whole notification array which is great but having a function to delete a single notification can also be useful. We might want to delete only one or two notifications instead of the whole notification array at once. 

2) Could you resolve the conflict in the app.py file? 

3) Could you change the name of the class from "Notification" to "QuestionNotification"? I believe your class is handling notifications for questions only so we will have another class which handles the notifications for all answers.

**Review by DrakeHunterK7 — CHANGES_REQUESTED** [review]
Oh and can you also add another boolean variable for a notification object called "checked". This variable will be used to check if this notification was already seen and clicked on by the user. True means this notification was checked out by the user, False means this notification is not yet checked out by the user (the user hasn't clicked on the notification)

**Comment by ChenChenYellow** [comment]
image
The PUT request will take 
Type [string]
Question_ID [string]
Answer_ID [string] (Optional)

The PUT method is a replacement of current DELETE method.
The PUT method will set Notifications of a specific Answer or Question to Viewed == True.
The GET method will not show Notifications with Viewed == True.
This way we don't need to delete Notifications, we just set the Viewed to True.

mongodb

**Comment by ChenChenYellow** [comment]
> Oh and can you also add another boolean variable for a notification object called "checked". This variable will be used to check if this notification was already seen and clicked on by the user. True means this notification was checked out by the user, False means this notification is not yet checked out by the user (the user hasn't clicked on the notification)

Sure

**Comment by ChenChenYellow** [comment]
> Hi, bro. Looks good overall. Just three things:
> 
> 1. Could you add one more delete function that deletes only one individual notification from the notification array? You already have a delete function for deleting the whole notification array which is great but having a function to delete a single notification can also be useful. We might want to delete only one or two notifications instead of the whole notification array at once.
> 2. Could you resolve the conflict in the app.py file?
> 3. Could you change the name of the class from "Notification" to "QuestionNotification"? I believe your class is handling notifications for questions only so we will have another class which handles the notifications for all answers.

For the DELETE method, it will be replace by PUT.
we will change the Viewed == True for Notifications of specific Question/Answer.
That way we don't need to delete stuff.

And GET/PUT of /notifications can handle Answer Notifications as well. 
For Question Notifications, there will not be an Answer_ID
For Answer Notifications, there will be an Answer_ID.
The PUT can differentiate them

**Review by DrakeHunterK7 — CHANGES_REQUESTED** [review]
Last thing. So far your Notification class sends a notification when user gets a vote on their question or gets an answer to their question.

Could you also add code to send and receive notification when user gets a vote on their answer and when their answer gets declared as best answer?

**Comment by ChenChenYellow** [comment]
> Last thing. So far your Notification class sends a notification when user gets a vote on their question or gets an answer to their question.
> 
> Could you also add code to send and receive notification when user gets a vote on their answer and when their answer gets declared as best answer?
image
Now a Notification will be added whenever
1. a Question Owner receive a new Vote on his Question
[type] : "Vote"
[vote_change] : -2/-1/0/1/2 
[questionID] : an UUID

2. a Question Owner receive a new Answer under his Question
[type] : "Answer"
[questionID] : an UUID

3. an Answer Owner receive a new Vote on his Answer
[type] : "Vote"
[vote_change] : -2/-1/0/1/2 
[questionID] : an UUID
[answerID] an UUID

4. an Answer Owner receive a Best Answer tag on his Answer
[type] : "Best Answer"
[questionID] : an UUID
[answerID] an UUID

**Comment by DrakeHunterK7** [comment]
Now the notification types have been changes as follows:

-"Vote" type for VoteQuestion method has been changed to "VoteQuestion"
-"Vote" type for VoteQuestion method has been changed to "VoteQuestion"

**Review by DrakeHunterK7 — APPROVED** [review]
Great work @ChenChenYellow !

Everything looks great. Pull Request Approved!

**Pull request merged**
